version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=frog*978
      - POSTGRES_DB=shortLinks
    volumes:
      - postgresShortLinksDev:/bitnami/postgresql

  redis:
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=frog*978
    volumes:
      - redisShortLinksDev:/bitnami/redis

volumes:
  postgresShortLinksDev:
  redisShortLinksDev: